"""Convert the trained model to full-int8 TFLite and export firmware artifacts.

Outputs:
  out/kws.tflite               int8 in/out, ready for the Axon compiler
  ../firmware/generated/testvec.rs   embedded self-test vectors:
      - raw PCM of one test clip + its float features (frontend check)
      - quantized input + expected int8 logits (NPU check)

Also reports float vs int8 test accuracy so quantization loss is visible.
"""

from pathlib import Path

import numpy as np
import tensorflow as tf

from features import LABELS, NUM_FRAMES, NUM_MFCC, mfcc_batch, mfcc_single

OUT = Path("out")
FW_GEN = Path("../firmware/generated")
SEED = 99


def representative_dataset():
    x = np.load(OUT / "train_x.npy", mmap_mode="r")
    rng = np.random.default_rng(SEED)
    idx = rng.choice(len(x), 300, replace=False)
    noise = np.load(OUT / "noise.npy")
    for i in idx:
        pcm = x[i].astype(np.float32) / 32768.0
        yield [mfcc_batch(pcm[None])[..., None].astype(np.float32)]
    # cover the silence/noise feature range too
    for _ in range(30):
        start = rng.integers(0, len(noise) - 16000)
        pcm = noise[start : start + 16000].astype(np.float32) / 32768.0
        pcm *= rng.uniform(0.0, 0.3)
        yield [mfcc_batch(pcm[None])[..., None].astype(np.float32)]


def main():
    model = tf.keras.models.load_model(OUT / "kws_best.keras")

    conv = tf.lite.TFLiteConverter.from_keras_model(model)
    conv.optimizations = [tf.lite.Optimize.DEFAULT]
    conv.representative_dataset = representative_dataset
    conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    conv.inference_input_type = tf.int8
    conv.inference_output_type = tf.int8
    tflite = conv.convert()
    (OUT / "kws.tflite").write_bytes(tflite)
    print(f"kws.tflite: {len(tflite)} bytes", flush=True)

    interp = tf.lite.Interpreter(model_content=tflite)
    interp.allocate_tensors()
    inp_d = interp.get_input_details()[0]
    out_d = interp.get_output_details()[0]
    in_scale, in_zp = inp_d["quantization"]
    print(f"input quant: scale={in_scale} zp={in_zp}", flush=True)

    def infer_q(q_feats):
        interp.set_tensor(inp_d["index"], q_feats[None].astype(np.int8))
        interp.invoke()
        return interp.get_tensor(out_d["index"])[0]

    def quantize(feats):
        return np.clip(np.round(feats / in_scale + in_zp), -128, 127).astype(np.int8)

    # int8 accuracy on the full test set
    test_x = np.load(OUT / "test_x.npy", mmap_mode="r")
    test_y = np.load(OUT / "test_y.npy")
    correct = 0
    for off in range(0, len(test_x), 512):
        chunk = test_x[off : off + 512].astype(np.float32) / 32768.0
        feats = mfcc_batch(chunk)[..., None]
        for f, label in zip(feats, test_y[off : off + 512]):
            correct += int(np.argmax(infer_q(quantize(f))) == label)
    print(f"int8 test accuracy: {correct / len(test_y):.4f}", flush=True)

    # --- firmware test vector: first test clip of class "yes" that the int8
    # model classifies correctly.
    yes = LABELS.index("yes")
    for i in np.flatnonzero(test_y == yes):
        pcm = np.asarray(test_x[i])
        feats = mfcc_single(pcm)[..., None]
        q = quantize(feats)
        logits = infer_q(q)
        if int(np.argmax(logits)) == yes:
            break
    else:
        raise SystemExit("no correctly-classified 'yes' clip found")

    FW_GEN.mkdir(exist_ok=True)

    def fmt(arr, fmt_one):
        return ", ".join(fmt_one(v) for v in arr)

    rs = f"""// Generated by training/convert.py. Do not edit.
// Self-test vectors: clip test_x[{i}] (label "yes"), int8 interpreter logits.
pub const TV_LABEL: usize = {yes};
pub const TV_IN_SCALE: f32 = {in_scale!r};
pub const TV_IN_ZP: i32 = {in_zp};
pub static TV_PCM: [i16; {len(pcm)}] = [{fmt(pcm, lambda v: str(int(v)))}];
pub static TV_FEATS: [f32; {NUM_FRAMES * NUM_MFCC}] = [{fmt(feats.flatten(), lambda v: f"{v:.8e}")}];
pub static TV_INPUT_Q: [i8; {NUM_FRAMES * NUM_MFCC}] = [{fmt(q.flatten(), lambda v: str(int(v)))}];
pub static TV_LOGITS: [i8; {len(logits)}] = [{fmt(logits, lambda v: str(int(v)))}];
pub static LABEL_NAMES: [&str; {len(LABELS)}] = [{fmt(LABELS, lambda v: f'"{v}"')}];
"""
    (FW_GEN / "testvec.rs").write_text(rs)
    print(f"wrote {FW_GEN / 'testvec.rs'}", flush=True)


if __name__ == "__main__":
    main()
